### ISSUE TITLE
Provided Atom stylesheet no longer works

### ISSUE THREAD

**Issue by gsklee** [larsenwork/monoid#175]
Atom stylesheet: https://gist.github.com/larsenwork/255432b5101093fb07bc

It no longer works in Atom v1.13.0; the issue seems to be three-fold:

1. Shadow DOM is no longer being used in Atom since v1.13.0, so I changed the stylesheet to:

```css
atom-text-editor .cursor-line {
  -webkit-font-feature-settings: "liga" off, "calt" off;
}
```

2. Still doesn't work; turned out `font-feature-settings` is no longer prefixed [since Chrome v48](https://developer.mozilla.org/en/docs/Web/CSS/font-feature-settings), so changed my stylesheet to:

```css
atom-text-editor .cursor-line {
  font-feature-settings: "liga" off, "calt" off;
}
```

3. Still doesn't work; turned out the `font-feature-settings` property is not being inherited by child elements:

#### `.cursor-line` has `"liga" off, "calt" off`
![http://i.imgur.com/tMiU3lU.png](http://i.imgur.com/tMiU3lU.png)

#### Not so true for its descendents
![http://i.imgur.com/y5z8bml.png](http://i.imgur.com/y5z8bml.png)

Baffled by the third one because the property should be inherited according to the MDN docs.

**Comment by gsklee** [comment]
Can be fixed with:

```css
* {
  -webkit-font-smoothing: antialiased;
  font-feature-settings: "liga" on, "calt" on;
}

atom-text-editor .cursor-line span {
  font-feature-settings: "liga" off, "calt" off;
}
```

Probably related: https://github.com/w3c/csswg-drafts/issues/552
